workflows:
  ios-app:
    name: iOS App Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      ios_signing:
        distribution_type: app_store # Hoặc 'development' để test
        bundle_identifier: app_store
      vars:
        XCODE_SCHEME: "YourAppName"
        XCODE_PROJECT: "./platforms/ios/YourAppName.xcodeproj"
      node: 16.14.0 # Phiên bản Node.js, tùy thuộc vào dự án
      xcode: latest # Hoặc phiên bản cụ thể, ví dụ "15.0"
      cocoapods: 1.11.3
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g cordova
          cordova platform add ios
      - name: Install CocoaPods
        script: |
          cd platforms/ios
          pod install
      - name: Build iOS app
        script: |
          cordova build ios --device --release
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
    publishing:
      email:
        recipients:
          - vuongcdt@gmail.com
        notify:
          success: true
          failure: true